### ISSUE TITLE
Stereo channels end up reversed on Debian Sid

### ISSUE THREAD

**Issue by Djhg2000** [duncanthrax/scream#10]
Not sure if this is distro/version specific but somehow sounds from Windows get the channels reversed, meanwhile sounds played within Debian are mapped correctly.

It's not clear to me where in the chain the channels get reversed, is there any known way to play the network stream with mpv or vlc for debugging?

**Comment by Djhg2000** [comment]
As if by magic the channel order fixed itself after submitting this issue. I will need to do further testing to come up with a reproducible test case.

**Comment by duncanthrax** [comment]
There might be a 50% chance of that happening if you launch the receiver into a running stream. The transmitted data is the raw PCM dump coming out of the Windows software audio subsystem. The receiver might start reading the stream at a packet that begins with an "R" frame. The channel order should correct itself when the source (Windows) has no clients playing, and the receiver runs empty on its PA buffer.

I'll do some research to see if it's possible to tweak the packet size so it's guaranteed to start with an "L" frame.
