### ISSUE TITLE
Multiple sources single client?

### ISSUE THREAD

**Issue by sammoth** [duncanthrax/scream#103]
Hi, from reading the readme, it sounds like Scream wouldn't be suitable for using in an environment with two scream sources on the same network playing to a single receiver, is this right? For example, two PCs playing audio and one receiver attached to a stereo?

**Comment by duncanthrax** [comment]
As long as the two sources don't play at the same time, it would work out of the box.
If you want to mix, set up the registry to use unicast and use two different ports, run two copies of the receiver and let pulseaudio mix it.

**Comment by sammoth** [comment]
Ah yes I missed the port option on the receiver. Sounds good, thanks
