### ISSUE TITLE
How fast it is under best condition? What's the minimum latency / delay time?

### ISSUE THREAD

**Issue by jmar83** [duncanthrax/scream#111]
Hi there

How fast it is under best condition? What's the minimum latency / delay time?

Thank you for your feedback.

Best regards,
Jan

**Comment by jmar83** [comment]
No anwser!?

**Comment by duncanthrax** [comment]
I never did a measurement. The latency up to the receiver on a local gigabit network should be sub 1ms. The kernel driver just dumps raw PCM data from the Windows sound subsystem into UDP packets via in-kernel winsock. No userspace, kernel thread. I don't think you can be any faster than that.

On the receiver, it depends. Pulse has it's own buffers. I think typical lag should be between 20-50 ms.

**Comment by jmar83** [comment]
-> https://github.com/duncanthrax/scream/issues/123

**Comment by jmar83** [comment]
...
