### ISSUE TITLE
scream ouput console strange

### ISSUE THREAD

**Issue by garffi** [duncanthrax/scream#122]
Hello,

I have a windows vm and have configured to use scream with ivshmem. I host is manjaro.

I run my command under the host, and I have a weird, characterful result that scrolls when I play sound, as if the console is pulling out the ouput:

```
 �F��fr����% �X�.� () P▒��0L�▒ ۋ� $ �q��0vv t�����x � 
                                                 ���5�TM8�I
F�L����z�x / ��3H��O���0��B��P���6�`�L�`��� ���pd'����� �B� \ ��K���o���H��`���F ^
 � & ��� �� 4] p3 @ {� 
       �v��ǧ d�� @ tI��`x��`▒�xg (���h [X���▒! ����aW�M��-��j46�D��� fM���4�D% M�p����� � @ ҏ���������P�i�p��� @ & ���Nn�����Fd�� ▒����> 8Xc��0 * p� =
 ����> � 
       ���]
          4Y���: �X ("� ܹ <���0��� u�� �A�p̭���: �`m��l���p�R� ^ ����R� (��4��L�N� * G | ������� "��_��0�K�Px�� أ���������� x���O & � ��� @% _ ���c`� $
                                                                                                                               � [�5� 
```

I also tried the network interface and it's the same result.

Do you have an idea of ​​the problem?

**Comment by martinellimarco** [comment]
Hi,

can you post the exact commands you are executing?

**Comment by garffi** [comment]
> Hi,
> 
> can you post the exact commands you are executing?

simply **scream -m /dev/shm/scream-ivshmem** or **scream -i virbr0**

**Comment by martinellimarco** [comment]
If you compiled it yourself check if you have libpulse-dev or libasound2-dev.
It sounds like you didn't have any of these and so the default output reverted to raw which is what you are seeing there.

See the instructions in the [README.md](https://github.com/duncanthrax/scream/tree/master/Receivers/unix#pulseaudio) file

**Comment by garffi** [comment]
yes i have to recompile with pkgbuild, i must be missing a lib. Sorry for the weakness of my request

**Comment by martinellimarco** [comment]
you are welcome. Close this issue if it's fixed, thank you.

**Comment by garffi** [comment]
thanx for help
