### ISSUE TITLE
certificate problem

### ISSUE THREAD

**Issue by kosuodhmwa** [duncanthrax/scream#123]
Die digitale Signatur der für dieses Gerät erforderlichen Treiber kann nicht überprüft werden. Bei einer vor Kurzem durchgeführten Änderung an Hardware oder Software wurde möglicherweise eine Datei installiert, die falsch signiert oder beschädigt ist. Möglicherweise handelt es sich auch um schädliche Software einer unbekannten Quelle. (Code 52)

...get that message in device mananger. how to uninstall?

**Comment by jayjupdhig** [comment]
same problem here but no solution! :-(

**Comment by jayjupdhig** [comment]
???

**Comment by tonyzzz321** [comment]
https://github.com/duncanthrax/scream#installation-on-windows-10-version-1607-and-newer

**Comment by jayjupdhig** [comment]
OK thx, will look about it...

**Comment by jmar83** [comment]
does not work - why?

thank you for your feedback.


with kind regards,
jan

**Comment by jmar83** [comment]
?????

**Comment by kosuodhmwa** [comment]
Problem solved by ignoring your crap... ;-)
