### ISSUE TITLE
can vlc be used as a receiver on windows? howto?

### ISSUE THREAD

**Issue by SteveDevOps** [duncanthrax/scream#124]
trying to use vlc as a unicast receiver in windows. running source windows (scream) machine as unicast. Trying to do this: https://www.advanceddigital.com/blog/using-vlc-multicast-unicast-udp-streams/

**Comment by SteveDevOps** [comment]
I get a "VLC cound not identify the audio or video codec.."

**Comment by duncanthrax** [comment]
That won't work, Scream does not use a standard streaming format.

I had a version with RTP support once, but it's not practical to use because Scream does not send silence when there's no sound but actually stops the stream.
