### ISSUE TITLE
Stereo channel swap randomly on sleep, hibernation [or after silence if silence suppression is on] of the sender system (Windows 10)

### ISSUE THREAD

**Issue by A2K** [duncanthrax/scream#148]
Silence suppression swaps the audio channels randomly. About half the times when there is nothing playing the audio channels get swapped.

This is easy to test by setting one of the audio channels volume to 50% like this:
![image](https://user-images.githubusercontent.com/48781/127692135-c38f6d80-1d0b-48c0-87ee-c16a2e80aadd.png)

**Comment by A2K** [comment]
May be related to the issue described here: https://github.com/duncanthrax/scream/issues/10#issuecomment-393991430

**Comment by duncanthrax** [comment]
@andyclegg : Can you take a look please?

**Comment by andyclegg** [comment]
@duncanthrax I was working on this at my old job, unfortunately I've moved on now so won't be able to work on this any more. I believe @gabrielsteadman has taken over work on this.

**Comment by A2K** [comment]
Unfortunately, the issue with channel swapping is also reproducible without silence suppression. The channels have a 1/2 chance to swap every time my sender PC goes to sleep or hybernates.

**Comment by EpicatSupercell** [comment]
I've used wireshark to check the packets going on the network (unicast), and the issue is on the sender (Windows 10) side.

**Comment by EpicatSupercell** [comment]
I've found a possible issue with silence suppression and the fix seem to solve it, but it doesn't explain the sleep / hibernation part.
I couldn't check it myself since I didn't encounter it before, there is a chance that will fix itself as well but who knows.
