### ISSUE TITLE
Windows 10 Audio to Raspberry Pi 3

### ISSUE THREAD

**Issue by kiam001** [duncanthrax/scream#149]
Hello i search for a aplication to send 5.1 audio over lan to pi from windows 10

audio worked but swapped complete wrong any fix to fix 5.1 to right speaker
Your device doesn't support channel maps. Channels may be in the wrong order.
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred

**Comment by kiam001** [comment]
channel map is
right = right
left = left
center = rear left
lfe = rear right
rear left = center
rear right = lfe

**Comment by duncanthrax** [comment]
You can remap in ALSA. Pointer: https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture/Troubleshooting#HDMI_5.1_sound_goes_to_wrong_speakers

**Comment by kiam001** [comment]
pcm.51kiam {
     type route
     slave.pcm surround51:ICUSBAUDIO7D
     # hier wurde das vordefinierte Gerät "surround51" verwendet
     # falls "dmixer" entsprechend konfiguriert wurde, kann man ihn als slave.pcm angeben
     slave.channels 6
     ttable.0.0 1      # front links
     ttable.1.1 1      # front rechts
     ttable.2.4 1  # hinten links
     ttable.3.5 1  # hinten rechts
     ttable.4.2 1    # zentrum
     ttable.5.3 1   # basskanal
}

thx works
