### ISSUE TITLE
Broken audio over wired network

### ISSUE THREAD

**Issue by pylad** [duncanthrax/scream#15]
Hi!

This issue is probably specific to me, I was just wondering if you could give me any pointers to what might be the root of the issue. So on my network running scream sever, the audio works fine on all clients connecting through wifi but it's all the wired gigabit LAN client that having issues and it's completely unusable whether it's Linux, Raspberry PI or Windows7/10, the sound coming through is broken, garbled glitchy mess, I've ruled out everything, it must be network issue, I tried different routers even but still same results. You can still make out the sound but it's very bad. So I'm wondering where exactly could be the issue? So maybe some IGMP setting on the router? I have no idea what's exactly relevant to Scream or not. I'd appreciate any tip on what kind of network setup scream needs.

**Comment by duncanthrax** [comment]
Hard to say. Surprising that WiFi clients work :)

When you say "different router", did you really mean "different switch"?

Garbled sound means packet loss. Some kind of rate limiting maybe?

If it would be IGMP issues, you'd hear nothing at all or it would cut out after a couple seconds.
