### ISSUE TITLE
Configure which interface scream uses on windows

### ISSUE THREAD

**Issue by leifwalsh** [duncanthrax/scream#171]
I use WSL on windows, which appears to create a virtual Ethernet interface in addition to my physical one. Sometimes (can't tell when or why, sometimes rebooting resets it) scream output goes over the virtual interface, and doesn't reach my linux box. I can tell by looking at bandwidth use in Task Manager. 

Is there or could there be a way to tell scream to stick to the physical interface? (Maybe this is unicast? I don't know much about networks. I tried to configure that and it didn't help, but maybe I did it wrong?)

**Comment by duncanthrax** [comment]
Check this out:
https://github.com/duncanthrax/scream/issues/7

However, unicast should also have solved the problem.

**Comment by leifwalsh** [comment]
Thanks! Will reopen if I can't figure this out.

**Comment by leifwalsh** [comment]
The first link there worked perfectly, thanks again!
