### ISSUE TITLE
wont compile

### ISSUE THREAD

**Issue by wioo** [duncanthrax/scream#185]
`/build/scream-git/src/scream/Receivers/unix/scream.c: In function ‘main’:
/build/scream-git/src/scream/Receivers/unix/scream.c:224:73: error: ‘stream_name’ undeclared (first use in this function); did you mean ‘pa_stream_name’?
  224 |       if (pulse_output_init(target_latency_ms, max_latency_ms, pa_sink, stream_name) != 0) {
      |                                                                         ^~~~~~~~~~~
      |                                                                         pa_stream_name
/build/scream-git/src/scream/Receivers/unix/scream.c:224:73: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/scream.dir/build.make:76: CMakeFiles/scream.dir/scream.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/scream.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

Should stream_name in line 224
      if (pulse_output_init(target_latency_ms, max_latency_ms, pa_sink, stream_name) != 0) {

be pa_stream_name?

**Comment by duncanthrax** [comment]
Thanks for reporting, please try again :)
