### ISSUE TITLE
Installation fails on Windows 11 ARM64

### ISSUE THREAD

**Issue by YoungerDryas89** [duncanthrax/scream#199]
Hi there, I've been trying to install this driver and so far, I've used workaround #2 and have disabled secure boot. Here is more information about my machine and my output:

Device name	DESKTOP-DQRVMCP
Processor	Snapdragon (TM) 7c Gen 2 @ 2.55 GHz   2.55 GHz
Installed RAM	4.00 GB (3.68 GB usable)
System type	64-bit operating system, ARM-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	21H2
Installed on	‎4/‎11/‎2022
OS build	22000.1455
Experience	Windows Feature Experience Pack 1000.22000.1455.0

My output: 
`Device node created. Install is complete when drivers are installed...
Updating drivers for *Scream from C:\Users\Andres Vazquez\Downloads\Scream4.0\Install\driver\arm64\Scream.inf.
devcon-arm64 failed.`

**Comment by swstegall** [comment]
This can likely be fixed by referencing the instructions update made as part of #213. Feel free to follow the instructions listed there and it should fix the Scream installation for you in Windows 11.
