### ISSUE TITLE
Blue screen while install driver on windows 7

### ISSUE THREAD

**Issue by yzp-fish** [duncanthrax/scream#214]
tried to install the driver with driver signing disabled ,but it still gave me a blue screen
![IMG_0994](https://github.com/duncanthrax/scream/assets/159319412/0dc3cd59-d62b-4409-a820-ae63248b7476)

**Comment by duncanthrax** [comment]
Not sure if the more recent versions have a problem with W7. It's been EOL for a while :)

Please try one of the older versions, 3.0 has basically all of the features and should be stable: https://github.com/duncanthrax/scream/releases/tag/3.0
