### ISSUE TITLE
Installation fails on Windows 11

### ISSUE THREAD

**Issue by FeralFox** [duncanthrax/scream#218]
Hi!
I was using scream on my Windows 10 machine and it worked great. However, now I have a new PC that uses Windows 11 and I am not able to install scream anymore. This here is the output when I execute the .bat file with administrator privileges.

> Device node created. Install is complete when drivers are installed...
> Updating drivers for *Scream from C:\Users\Me\Downloads\Scream4.0\Install\driver\x64\Scream.inf.
> devcon-x64 failed.

Is there anything I can do to make this work?

Thank you :)

**Comment by TheTrustedComputer** [comment]
I have the same problem.

**Comment by netham45** [comment]
It's erroring out because the certificate is expired. I worked around it on mine by setting my clock to 2022 before installing.

**Comment by FeralFox** [comment]
> It's erroring out because the certificate is expired. I worked around it on mine by setting my clock to 2022 before installing.

Thank you very much, this helped! The error was a bit misleading though, as it didn't say that there was an issue with the certificate. 
I will close this ticket. As a quick fix a hint in the documentation would be great :)
