### ISSUE TITLE
Need clear PCM stream

### ISSUE THREAD

**Issue by khseal** [duncanthrax/scream#33]
Nice driver. I have been looking for such a driver for a long time.
Is it possible to make an option to send just a clear PCM stream via UDP?
I use this kind of magic on the device.
socat -u udp-listen:4444,reuseaddr,fork stdio |  aplay -q -f S16_BE -r 48000 -c 2
This works well, but the software that I use in Windows has limitations.
Some devices, it is difficult to cross-compile your receiver.

**Comment by duncanthrax** [comment]
Before I added the dynamic sampling rate feature, the stream was clear. So you can just use the last 1.x version for the time being. See the releases page.

What is the problem with compiling the receiver?

**Comment by khseal** [comment]
It's a long time to set up an environment for cross compiling, plus I'm not good at cross compiling.
Is there a client that sends a stream for Linux?
I can see stream receivers, but the sender does not. Only windows?

**Comment by khseal** [comment]
There is a problem with the libasound2-dev library when compiling.
There is no such library in entware. I do not know how to compile it ..

**Comment by khseal** [comment]
I managed to compile the receiver.
Here is the package for compiling in Entware or OpenWrt.

[scream.zip](https://github.com/duncanthrax/scream/files/2963663/scream.zip)

Errors occur during operation.
ALSA lib pcm.c: 8424: (snd_pcm_recover) underrun occurred
ALSA lib pcm.c: 8424: (snd_pcm_recover) underrun occurred
This is normal?
