### ISSUE TITLE
Scream IVSHMEM BSODs Windows 10 with invalid configuration

### ISSUE THREAD

**Issue by DragoonAethis** [duncanthrax/scream#41]
If the `UseIVSHMEM` DWORD in `HKLM\SYSTEM\CurrentControlSet\Services\Scream\Options` contains an invalid value (eg because that user didn't read the next paragraph and set it to `1` instead of the available shmem MBs *whistles*), the system BSODs on the first playback attempt w/ SYSTEM_SERVICE_EXCEPTION. OS is Windows 10 1903 (18362.86).

While BSODing is a very noticeable notification that the driver is misconfigured, it is also most likely not the best way to do so :)

**Comment by martinellimarco** [comment]
Ouch, good catch.
I can't believe I didn't test this scenario.
I'll patch it soon, tomorrow if I have time.

Thank you for reporting this issue.

**Comment by martinellimarco** [comment]
Hi @DragoonAethis 
it turned out that the fix was very easy so I've did it today.

You'll need to wait for @duncanthrax for signing and releasing the driver.

Thank you again for reporting this issue.

**Comment by duncanthrax** [comment]
Released as 3.2.

**Comment by DragoonAethis** [comment]
Wow, that was fast. Thanks!
