### ISSUE TITLE
ivshmem receivers getting stuck at "while (header->magic != 0x11112014)"

### ISSUE THREAD

**Issue by joe-p** [duncanthrax/scream#43]
I am running the a Windows 10 as root through libvirt (kvm/qemu), pulseaudio server is ran as non-root user on the host (Fedora 30, kernel 5.0.8-201.acspatch.fc30.x86_64 from the jlay-kernel-acspatch copr repo), root is connecting to the server as a client. For hardware I'm running a Ryzen 1700 on a B450 motherboard. 

/dev/shm/scream-ivshmem exists, with permissions rw-r--r-- 

I tried ivshmem-pulse as non-root but had errors opening the file. I thought this was odd since I had read permission, but now I know it's trying to open with read/write access so this makes sense. 

I then tried running it as root, only to discover that it's getting stuck in the while loop at line [106](https://github.com/duncanthrax/scream/blob/master/Receivers/pulseaudio-ivshmem/scream-ivshmem-pulse.c#L106)

```
Thread 1 "scream-ivshmem-" hit Breakpoint 1, main (argc=2, argv=0x7fffffffd768) at scream-ivshmem-pulse.c:106
106	      while (header->magic != 0x11112014) {
(gdb) c
Continuing.
```
I had one breakpoint at 106 and another at [109](https://github.com/duncanthrax/scream/blob/master/Receivers/pulseaudio-ivshmem/scream-ivshmem-pulse.c#L109), which was never reached. 

I gave the non-root user write permission (for /dev/shm/scream-ivshmem) and tried to run the script again, but encountered the same problem. 

I thought this might have been related to hugepages, so I tried running the VM without hugepages and got the same result. 

I tested the raw receiver and also got stuck in the same place ([line 97](https://github.com/duncanthrax/scream/blob/master/Receivers/raw-ivshmem/scream-ivshmem-raw.c#L97)).

**Comment by martinellimarco** [comment]
That's a barrier to stop the receiver until the guest have not initialized the shared memory.
If it god stuck there it means that the guest driver have not initialized the shared memory.

What is the size of your IVSHMEM device? Have you set the value of UseIVSHMEM registry key to be equal to that size?

**Comment by martinellimarco** [comment]
@joe-p Thank you for pointing out that the receiver requires write permission. It was required in an earlier version, but not anymore. I've updated the code to open the IVSHMEM device in read only.

**Comment by joe-p** [comment]
> @joe-p Thank you for pointing out that the receiver requires write permission. It was required in an earlier version, but not anymore. I've updated the code to open the IVSHMEM device in read only.

Yeah I thought that was a bit weird since only read permissions were stated in the README. Glad I could at least help with that. 

As for the IVSHMEM device, it is indeed 2MB, and the registry key is set 

```
PS C:\Windows\system32> Get-ItemProperty -PATH HKLM:\SYSTEM\CurrentControlSet\Services\Scream\Options\ -Name "UseIVSHMEM"


UseIVSHMEM   : 2
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Scream\Options\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Scream
PSChildName  : Options
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```

I did notice, however, that the modify time is not changing on /dev/shm/scream-ivshmem. The access time is updating when it's getting opened by the receiver, but the contents are staying the same. For example, I started my VM this morning and have a 10 hour YouTube video playing. I have the "Scream (WDM)" speaker selected (and it's "outputting" sound according the volume mixer), yet the last modify was last night. I would assume the expected behavior is the file being written to by the Windows driver. 

Also, for my own sanity, I added a timeout counter that displays a debug message every three seconds while the program is in this while loop. Might be useful to implement in case anyone else has a similar issue so they aren't just staring at a blank prompt.

**Comment by martinellimarco** [comment]
May I ask you to post the hex dump of the shared memory header while the VM is playing something?

If you have xxd this is the command: `xxd -l 100 /dev/shm/scream-ivshmem`

Thanks

**Comment by martinellimarco** [comment]
Just to confirm this, are you running version 3.2?

**Comment by joe-p** [comment]
Yes, on windows I downloaded the 3.2 zip from the release page and on the host I just cloned the repo (last night, so effectively 3.2). I now also pulled the read/write changes on the host. 

The header seems to be all zeros while spotify is playing on the VM. Last modify time for /dev/shm/scream-ivshmem is still last night (I'm in EST, so about 10 hours ago). 

```
[joe@localhost pulseaudio-ivshmem]$ xxd -l 100 /dev/shm/scream-ivshmem
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000                                ....

```

**Comment by martinellimarco** [comment]
In windows, have you also installed the IVSHMEM driver from [here](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/) ?

**Comment by joe-p** [comment]
Ah... yep, that was it. After installing the driver and restarting the VM audio works great.

**Comment by martinellimarco** [comment]
@joe-p thanks for reporting that it's working now :)

@duncanthrax when you have time can you update the readme to remember users to install the IVSHMEM driver from the link above?
