### ISSUE TITLE
Support mono streams

### ISSUE THREAD

**Issue by solarsea** [duncanthrax/scream#47]
Great stuff by the way, even though I didn't manage to get it working via multicast, unicast is really good :)

Can you please support mono/mixed to mono streams as well ? It would reduce the throughput requirements when the output is mono - like most BT speakers for example.

My setup is a windows box, streaming to a raspi zero w, which in turn streams to ikea eneby 30 bluetooth speaker. Using a bluetooth dongle for the windows box would have worked as well, but it is no fun :)

**Comment by martinellimarco** [comment]
Scream does already support mono stream.
Go into windows audio settings, click the Scream card and then configure.
In the window that will open you should see a list of settings, from mono up to 7.1 surround.
Default is stereo, but go ahead and change it to mono. You can also change the sampling rate and sample size to match the ones of your bluetooth speaker.

**Comment by solarsea** [comment]
The 3.2 release doesn't list mono on my windows box - Windows 7 x64, SP1, running on a e1-1230v5 cpu.

Here are the options in the speaker setup dialog for the WDM device.

- stereo
- quadraphonic
- surround
- 3.1 surround
- 5.1 surround (rear speakers on the side)
- 5.1 surround (rear speakers in the back)
- 7.1 surround

**Comment by martinellimarco** [comment]
Ouch, my fault. I've introduced a regression in the latest version for the network version. I'll fix it in a day or two, sorry for that.

**Comment by martinellimarco** [comment]
I've published the code that will allow you to set mono. You'll need to wait for @duncanthrax to release a signed version.

**Comment by solarsea** [comment]
Thanks! Can it be built it using just just the free windows sdk, e.g. with compiler and make, without visual studio installed ?

**Comment by martinellimarco** [comment]
I'm not sure about that, what I know is that you'll also need the WDK installed.
I can share the compiled binaries with you but the problem is that they are not signed so you'll need to enable windows test mode to install and use them.
Windows will refuse to install unsigned drivers except in test mode.

**Comment by martinellimarco** [comment]
@solarsea the fix is in [version 3.3](https://github.com/duncanthrax/scream/releases/tag/3.3)

**Comment by solarsea** [comment]
Confirmed, it works now. Thanks!
