### ISSUE TITLE
How to listen by local ScreamReader?

### ISSUE THREAD

**Issue by 3bagorion33** [duncanthrax/scream#53]
I installed Scream driver and started ScreamReader. Default device is hardware soundcard. I expexted listen sound when I press test button in properites tab of Scream device. But I can not hear anything. When I configure Scream device to unicast to another local PC, I hear test sound.

I have router with OpenWRT. How to configure my system?

**Comment by martinellimarco** [comment]
Hi @3bagorion33 can you clarify what's your setup?
It doesn't make much sense to install both Scream driver and ScreamReader on the same windows machine but maybe you are using a VM ?

**Comment by jpmorrison** [comment]
Probably because scream driver binds to port 4010


```
netstat -na 

  UDP    0.0.0.0:4010           *:*

```

Anyway I can't get netcat to listen on my local machine for troubleshooting 

This looks like it's listening to 4010 though. scream driver transmits from source 4010 to destination 4010.
Is this required by Windows sockets? 

I would like to try scream using localhost so I can try with scream receiver/jack(?) pulseaudio in Cygwin.
Use cases would include sound with X or unix/Cygwin ports. 
I'm looking for an open source  way to route windows sound to Airplay/Chromecast which I can do with a remote forked-daapd server 

Maybe there's another free Windows driver that already does this?

**Comment by shodanx2** [comment]
Hello, I think I may have cracked it

In your folder 
`scream-master\Receivers\dotnet-windows`

first make a copy of ScreamReader to ScreamReader2

With this command

`xcopy ScreamReader ScreamReader2 /E /I /H`

<img width="1917" height="1394" alt="Image" src="https://github.com/user-attachments/assets/a3c55813-442d-428a-b1ee-1e4fbcd4913e" />

In your folder ScreamReader2, overwrite the following files

```
MainForm.cs
MainForm.Designer.cs
UdpWaveStreamPlayer.cs
```

By uncompressing the following zip file in `scream-master\Receivers\dotnet-windows\ScreamReader2`

[ScreamReaderModification.zip](https://github.com/user-attachments/files/30331360/ScreamReaderModification.zip)

And also, decompress this build.bat file in the folder `scream-master\Receivers\dotnet-windows\`

[ScreamReaderBuilder.zip](https://github.com/user-attachments/files/30331442/ScreamReaderBuilder.zip)

This will download Naudio.dll if there is internet access from 

Now your folder should look like this 

<img width="1633" height="984" alt="Image" src="https://github.com/user-attachments/assets/7d03ed34-432a-4d7f-852a-b98a8d78ae12" />

And you run build.bat

<img width="2082" height="1424" alt="Image" src="https://github.com/user-attachments/assets/4176f512-806d-49a4-bec4-914cc19dd242" />

This build both ScreamReader and ScreamReader2

Run the original 

`build\ScreamReader\ScreamReader.exe`

<img width="2027" height="630" alt="Image" src="https://github.com/user-attachments/assets/7e93edd4-0534-4493-8296-6b2991916cfa" />


And run the modified version

`build\ScreamReader2\ScreamReader.exe`

<img width="1812" height="711" alt="Image" src="https://github.com/user-attachments/assets/f267f3b4-bab0-4056-874c-91d54dfa74dc" />

However I couldn't get scream/screamreader to work, even the normal version so I couldn't test this.
