### ISSUE TITLE
No sound on Fedora Linux 31 host from Windows 10 guest with Scream with IVSHMEM and pulseaudio..

### ISSUE THREAD

**Issue by koreykaczor** [duncanthrax/scream#59]
I follow the instructions as stated, and am not getting any sound from pulseaudio. /dev/shm/scream-ivshmem is created on VM boot, but is an empty file and remains so even during audio playback with the Scream WDM listed as speakers in windows.

I think something is preventing it from writing to the IVSHMEM file. 

[korey@hydra a]$ cat /dev/shm/scream-ivshmem 

The above gives me no output at all. However, in my Windows VM I tried Red Hat's "ivshmem-test.exe" in virtio-win10-prewhql-0.1-161 and catting again gave me expected garbage binary output.

Otherwise I'm too tired and completely stumped on this one.

**Comment by martinellimarco** [comment]
I know you said you followed the instructions as stated, but have you set the UseIVSHMEM registry key with a value equals to the size of the IVSHMEM device?

**Comment by koreykaczor** [comment]
After triple checking I see that I named it as a QWORD rather than a DWORD. I'm not very familiar with Windows and should probably get new contact lens.

Appreciate the help! I was starting to think it was SELinux or something.
