### ISSUE TITLE
[Suggestion] Renice scream-* players on launch

### ISSUE THREAD

**Issue by netham45** [duncanthrax/scream#62]
I was getting occasional crackling in my audio when CPU load was high. I was able to largely resolve this when I reniced scream-pulse to -11, same as Pulse was. As a suggestion this could be done by the clients themselves.

**Comment by duncanthrax** [comment]
Good idea! Since negative values require root or fiddling with limits.conf I'll add an opportunistic try to renice. If it works, it works.
