### ISSUE TITLE
Can't get the SHMEM version of scream working

### ISSUE THREAD

**Issue by accumulator** [duncanthrax/scream#63]
When I'm using the multicast config, it works, but when I switch to SHMEM variant using the registry, no sound is picked up on the receiver (host) side. I quadruple-checked the registry key name, value and type (UseIVSHMEM, DWORD=2)

The Win10 guest has the virtual audio output device and the mixer is showing sound is played.

On the host side:
- /dev/shm/scream-ivshmem is created, and is user-readable, but a quick hexdump shows only zeroes
- scream-ivshmem-pulse attaches to pulseaudio, but no sound is coming through

I'm not using looking-glass, scream is the only shmem entry defined for the VM

Can't test with the scream-ivshmem-test.exe since the links I found to that executable are expired :(

Am I missing something?

**Comment by martinellimarco** [comment]
Hi there,
the scream-ivshmem-test was just a quick test during early development and it's not useful now.

I can think of 2 possible things right now.
- what is the size of /dev/shm/scream-ivshmem ? It must be 2 in your case (the value must match the UseIVSHMEM value).
- have you installed the IVSHMEM driver in windows? It's available from [here](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/)

**Comment by accumulator** [comment]
Ah so it's actually two drivers that must be installed? Scream and ivshmem? I was under the impression scream was itself a driver for the shared memory device.. 

Will test later today!

**Comment by martinellimarco** [comment]
Yes, you need both drivers installed.

**Comment by accumulator** [comment]
works perfectly now, thanks
