### ISSUE TITLE
Receiver for Linux (especially for Raspberry Pi)

### ISSUE THREAD

**Issue by mincequi** [duncanthrax/scream#65]
Hi,
I am developing a multi-protocol audio receiver for linux, which also supports scream.
Check it out here: https://github.com/mincequi/cornrow.
Currently, it only supports 44.1/48 kHz, Stereo, 16 Bit.

Testers welcome; please share your feedback :)

**Comment by duncanthrax** [comment]
Thanks, I added a note to the README! :)
