### ISSUE TITLE
Please keep Install directory synced with release assets

### ISSUE THREAD

**Issue by noscript** [duncanthrax/scream#72]
Assets in 3.4 release don't match with `3.4` tag.

`3.4` tagged:
```
$ md5sum Install/driver/*
d863785c9e4be2f7507a2920d7264a6f  Install/driver/scream.cat
3c9b55d6d981ff9525488042bf04b8f2  Install/driver/Scream.inf
ac9c1a464b53805ca8813ec333d8e7a0  Install/driver/Scream.sys
```

assets from release 3.4:
```
$ md5sum Install/driver/*
3b57f01d11361a9dcc5f5da162cdcf7f  Install/driver/scream.cat
41ffe89383e643f2266dfebe33e1dd69  Install/driver/Scream.inf
95cf29f9cd747e35b6bc7796eed219fb  Install/driver/Scream.sys
```

**Comment by duncanthrax** [comment]
Yeah, my workflow does not respect the fact that Github tags master with release tags.

The "master" branch was actually in sync with the lastest released version, but the "3.4" tag wasn't. I've now moved the tag. I'll keep this in mind for future releases.
