### ISSUE TITLE
ESP32 receiver

### ISSUE THREAD

**Issue by tomek-o** [duncanthrax/scream#87]
Hello,
I'd like to share very basic receiver based on ESP32 and PCM5102 codec: http://tomeko.net/projects/esp32_rtp_pager/
It is compact and inexpensive, although occasional packet loss (I'm guessing it might be WiFi itself) probably would make it not suitable for regular use.

**Comment by tomek-o** [comment]
One more close to bare metal receiver, but using wired connection: http://tomeko.net/projects/scream_eth/ - based on nucleo STM32F429ZI board, using built-in DACs.

**Comment by duncanthrax** [comment]
Hi Tomasz, thanks for the code, I've linked your site in the README. Cheers, /tom
