### ISSUE TITLE
Channel mapping

### ISSUE THREAD

**Issue by mqmq0** [duncanthrax/scream#88]
Hello!

Great project, I just discovered and started using, and so far its works fine, while I set the Windows device to stereo. As soon as I set it to multi channel (5.1 for example) I can see on the terminal, that the unix receiver is switches to 6 channel, but some weird combination of channels for some reason:
```

Using Pulseaudio output
xcb_connection_has_error() returned true
Starting multicast receiver
xcb_connection_has_error() returned true
Switched format to sample rate 48000, sample size 32 and 2 channels.
Channel 0 mapped to Front Right
Channel 1 mapped to Front Center
Channel 2 mapped to Rear Center
Channel 3 mapped to Side Left
Channel 4 mapped to Side Right
Channel 5 mapped to Side Right
xcb_connection_has_error() returned true
Switched format to sample rate 48000, sample size 32 and 6 channels.
Channel 0 mapped to Rear Center
Channel 1 mapped to Side Left
Channel 2 mapped to Side Right
Channel 3 mapped to Side Right
Channel 4 mapped to Side Right
Channel 5 mapped to Side Right
```
if I switch to Alsa:

```
Using ALSA output
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
Starting multicast receiver
xcb_connection_has_error() returned true
Your device doesn't support channel maps. Channels may be in the wrong order.
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
xcb_connection_has_error() returned true
```
My setup: Win10 PC as the source/server, ubuntu 18.04 HTPC as client connected to receiver with HDMI. 

I'm not sure where the problem is, with the receiver? With Pulseaudio? Something with the sound device on the client as the ALSA output says? 
What to do?
Let me know if you need more info!

**Comment by martinellimarco** [comment]
This is weird.
It seems like the channels are shifted for some reasons. Is that the whole pulseaudio output?
I see the channel list is printed twice but the second time it miss the "Switched format to.." line. Can you post the whole output?

In pulseaudio you have 5.1 output, right? What soundcard are you using?

**Comment by mqmq0** [comment]
So, full output of my current attempt:
I start with stereo, the modify the speaker setup on windows:

```
asd@asd:~/scream-master/Receivers/unix/build$ ./scream -i enp3s0 -v
Using Pulseaudio output
Starting multicast receiver
Switched format to sample rate 48000, sample size 32 and 2 channels.
Channel 0 mapped to Front Right
Channel 1 mapped to Front Center
Channel 2 mapped to Rear Center
Channel 3 mapped to Side Left
Channel 4 mapped to Side Right
Channel 5 mapped to Side Right
Switched format to sample rate 48000, sample size 32 and 6 channels.
Channel 0 mapped to Rear Center
Channel 1 mapped to Side Left
Channel 2 mapped to Side Right
Channel 3 mapped to Side Right
Channel 4 mapped to Side Right
Channel 5 mapped to Side Right
Switched format to sample rate 48000, sample size 32 and 6 channels.

```
The two 6 channel setup is when I switch between the two 5.1 option in windows:
![image](https://user-images.githubusercontent.com/13240971/80202311-f1a7df00-8614-11ea-81ce-39ed1c8b91b6.png)

My soundcard :

```
:~/scream-master/Receivers/unix/build$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC255 Analog [ALC255 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by martinellimarco** [comment]
I think I've found the problem, there was a regression when we merged all the receivers together.

I'm not at my dev pc right now to commit the fix but in network.c, line 36, can you replace

`receiver_data->format.channel_map = (rctx_network.buf[3] << 8) | rctx_network.buf[4];`

with

`receiver_data->format.channel_map = (rctx_network.buf[4] << 8) | rctx_network.buf[3];`

and see if it works?

The 3 and 4 in the square brackets are reversed.

**Comment by martinellimarco** [comment]
I've upstreamed the fix, thank you for reporting this regression.

**Comment by mqmq0** [comment]
Yes, i just had a chance to try it now, and its work fine now. Thanks!
