### ISSUE TITLE
Combining other libraries

### ISSUE THREAD

**Issue by viral98** [duncanthrax/scream#92]
Would combining another library that performs [noise reduction on audio](https://github.com/xiph/rnnoise) be possible with scream?

**Comment by duncanthrax** [comment]
On the Windows side, probably not. The implementation is running in kernel mode. It's theoretically possible to link in 3rd party code, but in practise you'll need a long time to work around the limitations.

On the receiver side, that can of course work. For example, pulseaudio has a pluggable filter module system.

**Comment by viral98** [comment]
Alright, thanks for the response!
