### ISSUE TITLE
Can't compile with pulseaudio / Mac

### ISSUE THREAD

**Issue by dFlamer** [duncanthrax/scream#97]
Hello, last year i got it to run with pulseaudio still as a receiver folder in macos, but today when i came back because i wanted to install it on a new machine i tried to cmake make what is inside the unix folder.

but unlike last time while i can install pulseaudio itself, i dont know how to make the scream file with pulseaudio

**Comment by martinellimarco** [comment]
Hi @dFlamer , what have you tried exactly?

I just tested it and it does compile on macOS Catalina

I did the following:

```bash
git clone https://github.com/duncanthrax/scream.git
cd scream/Receivers/unix/
cmake .
make
./scream -h
```

I already had pulseaudio installed with homebrew, I think I just did `brew install pulseaudio` but it was months ago.

Maybe you can post the output with the error?

**Comment by dFlamer** [comment]
1: Installing pulseaudio

brew install pulseaudio
```
==> Downloading https://homebrew.bintray.com/bottles/pulseaudio-13.0.catalina.bottle.tar.gz
Already downloaded: /Users/devy/Library/Caches/Homebrew/downloads/2f9e29759e5c6830e51a69171f7758807d5e5fd6b55550c166679000db6681e2--pulseaudio-13.0.catalina.bottle.tar.gz
==> Pouring pulseaudio-13.0.catalina.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

To have launchd start pulseaudio now and restart at login:
  brew services start pulseaudio
Or, if you don't want/need a background service you can just run:
  pulseaudio
==> Summary
🍺  /usr/local/Cellar/pulseaudio/13.0: 167 files, 4.8MB
```



git clone https://github.com/duncanthrax/scream.git

```
Cloning into 'scream'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 706 (delta 16), reused 22 (delta 9), pack-reused 661
Receiving objects: 100% (706/706), 1.17 MiB | 2.68 MiB/s, done.
Resolving deltas: 100% (397/397), done.
```

cd scream/Receivers/unix/

cmake .

```
-- The C compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/devy/scream/Receivers/unix
```

make
```
Scanning dependencies of target scream
[ 20%] Building C object CMakeFiles/scream.dir/scream.c.o
[ 40%] Building C object CMakeFiles/scream.dir/network.c.o
[ 60%] Building C object CMakeFiles/scream.dir/shmem.c.o
[ 80%] Building C object CMakeFiles/scream.dir/raw.c.o
[100%] Linking C executable scream
[100%] Built target scream
```

./scream -h
scream -h doesnt do anything, but if i use ./scream -p4011 i jsut get weird signs flying over the entire screen.

and if i do ./scream -o pulse it states:
./scream compiled without Pulseaudio support. Aborting

**Comment by martinellimarco** [comment]
Your problem is this: `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)``

Try to install it with `brew install pkg-config`

**Comment by dFlamer** [comment]
thank you, now i get another error tho,

> ./scream -o pulse -p 4011
```
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Unable to connect to PulseAudio. Connection refused
```

**Comment by martinellimarco** [comment]
Have you started pulseaudio? In another terminal run `pulseaudio -D`

**Comment by dFlamer** [comment]
Okay i did that, and i restarted once, the only thing is every macos sound i get from the monitor, but i dont get anything from the windows pc, 

however it does show up if i switch the settings on windows in my command line like:

```
> ./scream -o pulse -p 4011
Switched format to sample rate 48000, sample size 16 and 2 channels.
Switched format to sample rate 44100, sample size 16 and 2 channels.

```

**Comment by martinellimarco** [comment]
Uhm.. try to run pulseaudio in foreground mode to see the log

Kill the previous instance with `killall pulseaudio` and run `pulseaudio` without -D.

Launch scream again and look if pulseaudio is logging anything useful. Maybe it's selecting the wrong output port or the volume is zero?

**Comment by dFlamer** [comment]
nothing :(

```
> pulseaudio
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.


```

```
> ./scream -o pulse -p 4011
Switched format to sample rate 44100, sample size 24 and 2 channels.


```

**Comment by dFlamer** [comment]
Okay, i found the issue, its the Wireless Headphones, it sends it to Line in instead of my selected speaker option, well thats better than nothing for me :3 i actually like my analog headphones

**Comment by martinellimarco** [comment]
If you want you should be able can change the output device using `pacmd` or `pactl`. See [this](https://unix.stackexchange.com/questions/65246/change-pulseaudio-input-output-from-shell) for help.
